version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
      include:
        - "*"
    groups:
      all-dependencies:
        patterns:
          - "*"
    target-branch: main
    commit-message:
      prefix: "chore"
      include: "scope"
